site_name: Terraforming
site_description: San's Terraform Tutorial and Examples
site_url: https://sanspace.in/terraforming
repo_name: sanspace/terraforming
repo_url: https://github.com/sanspace/terraforming
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 Santhosh Kumar Srinivasan

nav:
  - Home: index.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  features:
    # nav
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.prune # not compatible with navigation.expand
    # header
    - header.autohide
    - announce.dismiss # allow users to mark announcements as read
    # footer
    - navigation.footer
    # toc
    - toc.follow
    - toc.integrate # not compatible with navigation.indexes
    - navigation.top # back to top
    # search
    - search.suggest
    - search.highlight
    - search.share
    # edit/view content
    - content.action.view
    - content.action.edit

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

plugins:
  - search
  - tags
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: sanspace/terraforming
      branch: main

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      anchor_linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  version:
    provider: mike